name: CI/CD Pipeline
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  release:
    types: [published]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run tests
      run: |
        pytest tests/ -v --cov=pywinauto_mcp --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  build-dxt:
    runs-on: windows-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Build DXT package
      run: |
        python dxt/build_dxt.py

    - name: Upload DXT package
      uses: actions/upload-artifact@v3
      with:
        name: dxt-package
        path: dist/*.dxt

  release:
    runs-on: windows-latest
    needs: [test, build-dxt]
    if: github.event_name == 'release'

    steps:
    - uses: actions/checkout@v4

    - name: Download DXT package
      uses: actions/download-artifact@v3
      with:
        name: dxt-package

    - name: Create GitHub release assets
      uses: softprops/action-gh-release@v1
      with:
        files: *.dxt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
